adapter:
  netbidib:
    enabled: true
    mode: server
    port: 62875
    node_name: BiDiB2WLED
  client:
    enabled: false

discovery:
  mdns: true
  interval: 30s
  timeout: 90s

web:
  host: 0.0.0.0
  port: 8080

controller: []
lamps: {}
houses: {}
groups: {}
sequences: {}
signals: {}
special: {}
vehicles: {}
