adapter:
  netbidib:
    aktiv: true
    modus: server
    port: 62875
    knotenname: BiDiB2WLED
  client:
    aktiv: false

erkennung:
  mdns: true
  intervall: 30s
  timeout: 90s

web:
  host: 0.0.0.0
  port: 8080

controller: []
lampen: {}
haeuser: {}
gruppen: {}
sequenzen: {}
signale: {}
spezial: {}
